In [1]:
# Importando as bibliotecas pandas e matplotlib

import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Lendo o arquivo csv já limpo

csv_file = r"C:\Users\josim\OneDrive\Área de Trabalho\ALINE\CC\COMPASS\scholarship-compass\Sprint_3\Desafio\etapa-1\csv_limpo.csv"

df = pd.read_csv(csv_file)
df

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,Start year,End year
0,1,780000000.0,780000000.0,Taylor Swift,The Eras Tour,56,13928571.0,2023,2024
1,2,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,56,10353571.0,2023,2023
2,3,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,85,4835294.0,2008,2009
3,4,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,156,2546795.0,2018,2019
4,5,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,53,6522173.0,2018,2018
5,6,305158363.0,388978496.0,Madonna,The MDNA Tour,88,3467709.0,2012,2012
6,7,280000000.0,381932682.0,Celine Dion,Taking Chances World Tour,131,2137405.0,2008,2009
7,8,257600000.0,257600000.0,Pink,Summer Carnival,41,6282927.0,2023,2024
8,9,256084556.0,312258401.0,Beyoncé,The Formation World Tour,49,5226215.0,2016,2016
9,10,250400000.0,309141878.0,Taylor Swift,The 1989 World Tour,85,2945882.0,2015,2015
10,11,229100000.0,283202896.0,Beyoncé,The Mrs. Carter Show World Tour,132,1735606.0,2013,2014
11,12,227400000.0,295301479.0,Lady Gaga,The Monster Ball Tour,203,1118227.0,2009,2011
12,13,204000000.0,251856802.0,Katy Perry,Prismatic World Tour,151,1350993.0,2014,2015
13,14,200000000.0,299676265.0,Cher,Living Proof: The Farewell Tour,325,615385.0,2002,2005
14,15,194000000.0,281617035.0,Madonna,Confessions Tour,60,3233333.0,2006,2006
15,16,184000000.0,227452347.0,Pink,The Truth About Love Tour,142,1295775.0,2013,2014
16,17,170000000.0,213568571.0,Lady Gaga,Born This Way Ball,98,1734694.0,2012,2013
17,18,169800000.0,207046755.0,Madonna,Rebel Heart Tour,82,2070732.0,2015,2016
18,19,167700000.0,204486106.0,Adele,Adele Live 2016,121,1385950.0,2016,2017
19,20,150000000.0,185423109.0,Taylor Swift,The Red Tour,86,1744186.0,2013,2014

Questão 1.

In [18]:
# Contando quantas vezes cada artista aparece na lista
artistas_contagem = df['Artist'].value_counts()
artistas_contagem

Artist
Taylor Swift    4
Madonna         4
Beyoncé         3
Pink            3
Lady Gaga       2
Celine Dion     1
Katy Perry      1
Cher            1
Adele           1
Name: count, dtype: int64

In [19]:
# Verificando qual o número máximo de aparições
max_aparicoes = artistas_contagem.max()
max_aparicoes

4

In [20]:
# Verificando quais artistas aparecem 4 vezes
artistas_mais_frequentes = artistas_contagem[artistas_contagem == max_aparicoes]
artistas_mais_frequentes

Artist
Taylor Swift    4
Madonna         4
Name: count, dtype: int64

In [21]:
# Filtrando apenas as artistas empatadas
artistas_empate = artistas_mais_frequentes.index.tolist()
artistas_empate

['Taylor Swift', 'Madonna']

In [22]:
# Calculando a média do faturamento bruto (Actual gross) dessas duas artistas
medias_empate = df.groupby("Artist")["Actual gross"].mean().loc[artistas_empate]
medias_empate

Artist
Taylor Swift    3.815188e+08
Madonna         2.699896e+08
Name: Actual gross, dtype: float64

In [23]:
# Verificando qual a artista que mais aparece e tem maior média de faturamento bruto
artista_mais_frequente = medias_empate.idxmax()
media_faturamento_artista = medias_empate.max()

artista_mais_frequente, media_faturamento_artista

('Taylor Swift', 381518786.5)

In [24]:
# Imprimindo a resposta da Questão 1
resposta_q1 = (
    f"Q1:\nA artista que mais aparece na lista e possui maior média de seu faturamento bruto é {artista_mais_frequente}, com média de ${media_faturamento_artista:,.2f} USD."
)

print(resposta_q1)

Q1:
A artista que mais aparece na lista e possui maior média de seu faturamento bruto é Taylor Swift, com média de $381,518,786.50 USD.

Questão 2.

In [12]:
# Verificando se existe pelo menos uma turnê que começou e terminou no mesmo ano
turnes_mesmo_ano = df[df["Start year"] == df["End year"]]
turnes_mesmo_ano

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,Start year,End year,Bruto por show
1,2,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,56,10353571.0,2023,2023,1.035357e+07
4,5,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,53,6522173.0,2018,2018,7.600846e+06
5,6,305158363.0,388978496.0,Madonna,The MDNA Tour,88,3467709.0,2012,2012,4.420210e+06
8,9,256084556.0,312258401.0,Beyoncé,The Formation World Tour,49,5226215.0,2016,2016,6.372620e+06
9,10,250400000.0,309141878.0,Taylor Swift,The 1989 World Tour,85,2945882.0,2015,2015,3.636963e+06
14,15,194000000.0,281617035.0,Madonna,Confessions Tour,60,3233333.0,2006,2006,4.693617e+06

In [13]:
# Selecionando qual dessas turnês que começaram e terminaram no mesmo ano teve a maior média de faturmento bruto ("Actual gross")
maior_gross = turnes_mesmo_ano.loc[turnes_mesmo_ano["Average gross"].idxmax()]
maior_gross

Rank                                                     2
Actual gross                                   579800000.0
Adjusted gross (in 2022 dollars)               579800000.0
Artist                                             Beyoncé
Tour title                          Renaissance World Tour
Shows                                                   56
Average gross                                   10353571.0
Start year                                            2023
End year                                              2023
Bruto por show                             10353571.428571
Name: 1, dtype: object

In [17]:
resposta_q2 = f"Q2:\nA turnê que aconteceu dentro de um único ano e teve a maior média de faturamento bruto (Average gross) foi '{maior_gross['Tour title']}' da artista {maior_gross['Artist']}, com média de faturamento de ${maior_gross['Average gross']:,.2f} USD."

print(resposta_q2)

Q2:
A turnê que aconteceu dentro de um único ano e teve a maior média de faturamento bruto (Average gross) foi 'Renaissance World Tour' da artista Beyoncé, com média de faturamento de $10,353,571.00 USD.

Questão 3.

In [3]:
# Criando uma coluna para o faturamento bruto por show
df["Bruto por show"] = df["Adjusted gross (in 2022 dollars)"] / df["Shows"]
df

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,Start year,End year,Bruto por show
0,1,780000000.0,780000000.0,Taylor Swift,The Eras Tour,56,13928571.0,2023,2024,1.392857e+07
1,2,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,56,10353571.0,2023,2023,1.035357e+07
2,3,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,85,4835294.0,2008,2009,6.595560e+06
3,4,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,156,2546795.0,2018,2019,2.915074e+06
4,5,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,53,6522173.0,2018,2018,7.600846e+06
5,6,305158363.0,388978496.0,Madonna,The MDNA Tour,88,3467709.0,2012,2012,4.420210e+06
6,7,280000000.0,381932682.0,Celine Dion,Taking Chances World Tour,131,2137405.0,2008,2009,2.915517e+06
7,8,257600000.0,257600000.0,Pink,Summer Carnival,41,6282927.0,2023,2024,6.282927e+06
8,9,256084556.0,312258401.0,Beyoncé,The Formation World Tour,49,5226215.0,2016,2016,6.372620e+06
9,10,250400000.0,309141878.0,Taylor Swift,The 1989 World Tour,85,2945882.0,2015,2015,3.636963e+06
10,11,229100000.0,283202896.0,Beyoncé,The Mrs. Carter Show World Tour,132,1735606.0,2013,2014,2.145476e+06
11,12,227400000.0,295301479.0,Lady Gaga,The Monster Ball Tour,203,1118227.0,2009,2011,1.454687e+06
12,13,204000000.0,251856802.0,Katy Perry,Prismatic World Tour,151,1350993.0,2014,2015,1.667926e+06
13,14,200000000.0,299676265.0,Cher,Living Proof: The Farewell Tour,325,615385.0,2002,2005,9.220808e+05
14,15,194000000.0,281617035.0,Madonna,Confessions Tour,60,3233333.0,2006,2006,4.693617e+06
15,16,184000000.0,227452347.0,Pink,The Truth About Love Tour,142,1295775.0,2013,2014,1.601777e+06
16,17,170000000.0,213568571.0,Lady Gaga,Born This Way Ball,98,1734694.0,2012,2013,2.179271e+06
17,18,169800000.0,207046755.0,Madonna,Rebel Heart Tour,82,2070732.0,2015,2016,2.524960e+06
18,19,167700000.0,204486106.0,Adele,Adele Live 2016,121,1385950.0,2016,2017,1.689968e+06
19,20,150000000.0,185423109.0,Taylor Swift,The Red Tour,86,1744186.0,2013,2014,2.156083e+06

In [4]:
# Selecionando as 3 turnês que possuem o show (unitário) mais lucrativo
top3 = df.sort_values("Bruto por show", ascending=False).head(3)
top3

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,Start year,End year,Bruto por show
0,1,780000000.0,780000000.0,Taylor Swift,The Eras Tour,56,13928571.0,2023,2024,1.392857e+07
1,2,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,56,10353571.0,2023,2023,1.035357e+07
4,5,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,53,6522173.0,2018,2018,7.600846e+06

In [30]:
resposta_q3 = (
    "Q3:\nAs 3 turnês mais lucrativas por show (em dólares ajustados de 2022):\n"
    f"1. {top3.iloc[0]['Tour title']} — {top3.iloc[0]['Artist']} — "
    f"Bruto por show: ${top3.iloc[0]['Bruto por show']:,.2f}\n"
    f"2. {top3.iloc[1]['Tour title']} — {top3.iloc[1]['Artist']} — "
    f"Bruto por show: ${top3.iloc[1]['Bruto por show']:,.2f}\n"
    f"3. {top3.iloc[2]['Tour title']} — {top3.iloc[2]['Artist']} — "
    f"Bruto por show: ${top3.iloc[2]['Bruto por show']:,.2f}"
)

print(resposta_q3)

Q3:
As 3 turnês mais lucrativas por show (em dólares ajustados de 2022):
1. The Eras Tour — Taylor Swift — Bruto por show: $13,928,571.43
2. Renaissance World Tour — Beyoncé — Bruto por show: $10,353,571.43
3. Reputation Stadium Tour — Taylor Swift — Bruto por show: $7,600,846.21